### ISSUE TITLE
Please specify which version of git is required

### ISSUE THREAD

**Issue by MachinesAreUs** [andybalaam/git-history-data#1]
Working with git v2.7 doesn't seem to work because a different format is expected from the output of `git show`

```
$ git-history-data
"Commit", "Date", "Author", "Added", "Removed", "File"
Traceback (most recent call last):
  File "/Users/agus/Development/workz/git-history-data/git-history-data", line 12, in <module>
    main( sys.argv, sys.stdout, sys.stderr )
  File "/Users/agus/Development/workz/git-history-data/githistorydata/main.py", line 18, in main
    for cod in expand_lines( git, expand_authors( git.log() ) ):
  File "/Users/agus/Development/workz/git-history-data/githistorydata/expand_commits.py", line 35, in expand_lines
    commit_detail = git.show( ln.commit_hash, ln.date, ln.author )
  File "/Users/agus/Development/workz/git-history-data/githistorydata/git.py", line 31, in show
    list( self._showline( l ) for l in show_lines[1:] if l != "")
  File "/Users/agus/Development/workz/git-history-data/githistorydata/git.py", line 31, in <genexpr>
    list( self._showline( l ) for l in show_lines[1:] if l != "")
  File "/Users/agus/Development/workz/git-history-data/githistorydata/git.py", line 67, in _showline
    % ln
Exception: Line from git show 'Author: Agustín Ramos Fonseca <zentimental.software@gmail.com>' did not match expected format
```

**Comment by andybalaam** [comment]
Thanks for reporting this - I'm going to take a look today.

With git 2.5 here it works OK for me, so that is a direct answer, but I will look into making it work with recent git versions.

**Comment by andybalaam** [comment]
@MachinesAreUs this was just a stupid bug, nothing to do with Git version - thanks for reporting it, and let me know if it's not fixed for you.

**Comment by MachinesAreUs** [comment]
It's fixed.
Thanks! :)

**Comment by andybalaam** [comment]
Brilliant, thanks for letting me know.
